### PR TITLE
Saksham teamB pull request

### PR DESCRIPTION
**Pull request by Saksham-Dhillon007**
Added content (added1) in file1
Added content (added2) in file2

### CODE REVIEW

**Review by shehenshah14 — CHANGES_REQUESTED** [review]
@Saksham-Dhillon007 please modify file3 as well

**Comment by Saksham-Dhillon007** [comment]
> @Saksham-Dhillon007 please modify file3 as well

Done! Added content (Added 3) in file3

**Review by shehenshah14 — CHANGES_REQUESTED** [review]
@praneeth1330 @Saksham-Dhillon007 Please merge both of your branch changes into one PR.

**Review by shehenshah14 — APPROVED** [review]
LGTM

**Pull request merged**
